- rfproxy fully implemented in POX. - rfstats is a new POX application to collect statistics and flows. - rfweb support removed from NOX. - Improvements in rfweb. - Unified rftest scripts for NOX and POX. - Improved scripts behavior in rftest. - Updated README.

diff --git a/rftest/rftest1 b/rftest/rftest1
--- a/rftest/rftest1
+++ b/rftest/rftest1
@@ -1,9 +1,30 @@
 #!/bin/bash
 
 if [ "$EUID" != "0" ]; then
-  echo "You must be root to run this script. Sorry, dude!"
+  echo "You must be root to run this script."
   exit 1
 fi
+
+ACTION=""
+case "$1" in
+--pox)
+    ACTION="POX"
+    ;;
+--nox)
+    ACTION="NOX"
+    ;;
+--reset)
+    ACTION="RESET"
+    ;;
+*)
+    echo "Invalid argument: $1"
+    echo "Options: "
+    echo "    --pox: run using POX"
+    echo "    --nox: run using NOX"
+    echo "    --reset: stop running and clear data from previous executions"
+    exit
+    ;;
+esac
 
 LXCDIR=/var/lib/lxc
 RF_HOME=..
@@ -19,62 +40,81 @@ ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
 	                 --certificate=db:SSL,certificate \
 	                 --bootstrap-ca-cert=db:SSL,ca_cert \
 	                 --pidfile --detach &>> $LOG_FILE
-ovs-vswitchd --pidfile --detach	&>> $LOG_FILE
+ovs-vswitchd --pidfile --detach &>> $LOG_FILE
 
-echo "Resetting and stopping LXC VMs..."
-rm -f $LXCDIR/{rfvm1,b1,b2}/rootfs/var/run/network/ifstate &>> $LOG_FILE
-lxc-stop -n b2 &>> $LOG_FILE
-lxc-stop -n b1 &>> $LOG_FILE
-lxc-stop -n rfvm1 &>> $LOG_FILE
+reset() {
+    echo "-> Stopping any running instances of rf-server, NOX, POX, OVS and MongoDB...";
+    pkill -15 rfserver;
+    pkill -15 python2.7;
+    pkill -15 lt-nox_core;
+    pkill -15 mongod;
 
-echo "Stopping any running instances and data of rfserver, NOX, OVS and MongoDB..."
-pkill -15 rfserver &> /dev/null
-pkill -15 lt-nox_core &> /dev/null
-pkill -15 mongod &> /dev/null
-rm -r $HOME/db &>> $LOG_FILE
-rm -r /var/lib/lxc/rfvm1/rootfs/opt/rfclient
+    sudo ovs-vsctl del-br br0;
+    sudo ovs-vsctl del-br dp0;
+    sudo ovs-vsctl del-br switch1;
+    sudo ovs-vsctl emer-reset;
+    
+    echo "-> Resetting and stopping LXC VMs...";
+    lxc-stop -n rfvm1;
+    lxc-stop -n b1;
+    lxc-stop -n b2;
+        
+    rm -rf $LXCDIR/rfvm1/rootfs/var/run/network/ifstate;
 
-sudo ovs-vsctl del-br br0
-sudo ovs-vsctl del-br dp0
-sudo ovs-vsctl del-br switch1
-sudo ovs-vsctl emer-reset
+    echo "-> Deleting data from previous runs...";
+    rm -rf $HOME/db;
+    rm -rf /var/lib/lxc/rfvm1/rootfs/opt/rfclient;
+}
+reset
+trap reset 2
 
-if [ "$1" != "clear" ]; then
-    echo "Starting MongoDB..."
+if [ "$ACTION" != "RESET" ]; then
+    echo "-> Starting MongoDB..."
     mkdir $HOME/db &>> $LOG_FILE
     mongod --quiet --dbpath $HOME/db --logpath /dev/null &
-    sleep 5
+    sleep 3
 
-    echo "Starting the rfvm1 virtual machine..."
+    echo "-> Starting the rfvm1 virtual machine..."
+    # Create the rfclient dir
     mkdir /var/lib/lxc/rfvm1/rootfs/opt/rfclient &>> $LOG_FILE
+
+    # Copy the rfclient executable
     cp build/rfclient /var/lib/lxc/rfvm1/rootfs/opt/rfclient/rfclient &>> $LOG_FILE
+
     cp /usr/lib/libmongoclient.a /var/lib/lxc/rfvm1/rootfs/usr/lib &>> $LOG_FILE
     cp /usr/lib/libmongoclient.so /var/lib/lxc/rfvm1/rootfs/usr/lib &>> $LOG_FILE
-    
+
     echo "#!/bin/sh" > /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
     echo "sleep 5" >> /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
     echo "/opt/rfclient/rfclient > /var/log/rfclient.log" >> /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
+
     chmod +x /var/lib/lxc/rfvm1/rootfs/root/run_rfclient.sh
-    
+
     lxc-start -n rfvm1 -d &>> $LOG_FILE
-
-
-    echo "Starting the management network (br0)..."
+    
+    echo "-> Starting the management network (br0)..."
     sleep 5
 	ovs-vsctl add-br br0 \
 		-- add-port br0 rfvm1.0 &>> $LOG_FILE
     ifconfig br0 up
     ifconfig br0 192.169.1.1
 
-    echo "Starting NOX and the RouteFlow network controller..."
-    ( cd nox/build/src && ./nox_core -i ptcp:6633 rfproxy --verbose="rfproxy:ANY:INFO" &>> $LOG_FILE & )
+    echo "-> Starting the controller ($ACTION) and RFPRoxy..."
+    case "$ACTION" in
+    POX)
+        ( cd pox && ./pox.py --no-cli log.level --=INFO topology openflow.topology openflow.discovery rfproxy rfstats & &>> $LOG_FILE & )
+        ;;
+    NOX)
+        ( cd nox/build/src && ./nox_core -i ptcp:6633 rfproxy --verbose="rfproxy:ANY:INFO" &>> $LOG_FILE & )
+        ;;
+    esac
     sleep 5
     
-    echo "Starting the RouteFlow server..."
+    echo "-> Starting the RFServer..."
     build/rfserver &>> $LOG_FILE &
     sleep 3
-    
-    echo "Starting the control plane network (dp0 OVS)..."
+
+    echo "-> Starting the control plane network (dp0 VS)..."
 	ovs-vsctl add-br dp0 \
 		-- add-port dp0 rfvm1.1 \
 		-- add-port dp0 rfvm1.2 &>> $LOG_FILE
@@ -82,8 +122,8 @@ if [ "$1" != "clear" ]; then
 	ovs-vsctl set-controller dp0 tcp:127.0.0.1:6633
     ifconfig dp0 up &>> $LOG_FILE
     sleep 3
-        
-    echo "Starting the sample network..."
+
+    echo "-> Starting the sample network..."
     lxc-start -n b1 -d &>> $LOG_FILE
     lxc-start -n b2 -d &>> $LOG_FILE
 	ovs-vsctl add-br switch1 \
@@ -94,13 +134,15 @@ if [ "$1" != "clear" ]; then
     
     cd - &> /dev/null
     sleep 5
-    
+
+    echo "---"    
     echo "Now we'll open this test's log."
     echo "Try pinging b1 from b2:"
     echo "  $ sudo lxc-console -n b1"
     echo "Login and run:"
     echo "  $ ping 172.31.2.2"
+    echo "You can stop this test by pressing CTRL+C."
+    echo "---"
     tail -f $LOG_FILE
 fi
-
 exit 0
diff --git a/rftest/rftest2 b/rftest/rftest2
--- a/rftest/rftest2
+++ b/rftest/rftest2
@@ -1,9 +1,30 @@
 #!/bin/bash
 
 if [ "$EUID" != "0" ]; then
-  echo "You must be root to run this script. Sorry, dude!"
+  echo "You must be root to run this script."
   exit 1
 fi
+
+ACTION=""
+case "$1" in
+--pox)
+    ACTION="POX"
+    ;;
+--nox)
+    ACTION="NOX"
+    ;;
+--reset)
+    ACTION="RESET"
+    ;;
+*)
+    echo "Invalid argument: $1"
+    echo "Options: "
+    echo "    --pox: run using POX"
+    echo "    --nox: run using NOX"
+    echo "    --reset: stop running and clear data from previous executions"
+    exit
+    ;;
+esac
 
 LXCDIR=/var/lib/lxc
 RF_HOME=..
@@ -19,41 +40,47 @@ ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
 	                 --certificate=db:SSL,certificate \
 	                 --bootstrap-ca-cert=db:SSL,ca_cert \
 	                 --pidfile --detach &>> $LOG_FILE
-ovs-vswitchd --pidfile --detach	&>> $LOG_FILE
-	
-echo "Resetting and stopping LXC VMs..."
-rm -f $LXCDIR/rfvmA/rootfs/var/run/network/ifstate &>> $LOG_FILE
-rm -f $LXCDIR/rfvmB/rootfs/var/run/network/ifstate &>> $LOG_FILE
-rm -f $LXCDIR/rfvmC/rootfs/var/run/network/ifstate &>> $LOG_FILE
-rm -f $LXCDIR/rfvmD/rootfs/var/run/network/ifstate &>> $LOG_FILE
+ovs-vswitchd --pidfile --detach &>> $LOG_FILE
 
-lxc-stop -n rfvmA &>> $LOG_FILE
-lxc-stop -n rfvmB &>> $LOG_FILE
-lxc-stop -n rfvmC &>> $LOG_FILE
-lxc-stop -n rfvmD &>> $LOG_FILE
+reset() {
+    echo "-> Stopping any running instances of rf-server, NOX, POX, OVS and MongoDB...";
+    pkill -15 rfserver;
+    pkill -15 python2.7;
+    pkill -15 lt-nox_core;
+    pkill -15 mongod;
 
-echo "Stopping any running instances and data of rf-server, NOX, OVS and MongoDB..."
-pkill -15 rfserver &> /dev/null
-pkill -15 lt-nox_core &> /dev/null
-pkill -15 mongod &> /dev/null
+    sudo ovs-vsctl del-br br0;
+    sudo ovs-vsctl del-br dp0;
+    sudo ovs-vsctl emer-reset;
+    
+    echo "-> Resetting and stopping LXC VMs...";
+    lxc-stop -n rfvmA;
+    lxc-stop -n rfvmB;
+    lxc-stop -n rfvmC;
+    lxc-stop -n rfvmD;
+        
+    rm -rf $LXCDIR/rfvmA/rootfs/var/run/network/ifstate;
+    rm -rf $LXCDIR/rfvmB/rootfs/var/run/network/ifstate;
+    rm -rf $LXCDIR/rfvmC/rootfs/var/run/network/ifstate;
+    rm -rf $LXCDIR/rfvmD/rootfs/var/run/network/ifstate;
 
-sudo ovs-vsctl del-br br0
-sudo ovs-vsctl del-br dp0
-sudo ovs-vsctl emer-reset
+    echo "-> Deleting data from previous runs...";
+    rm -rf $HOME/db;
+    rm -rf /var/lib/lxc/rfvmA/rootfs/opt/rfclient;
+    rm -rf /var/lib/lxc/rfvmB/rootfs/opt/rfclient;
+    rm -rf /var/lib/lxc/rfvmC/rootfs/opt/rfclient;
+    rm -rf /var/lib/lxc/rfvmD/rootfs/opt/rfclient;
+}
+reset
+trap reset 2
 
-rm -r $HOME/db &>> $LOG_FILE
-rm -r /var/lib/lxc/rfvmA/rootfs/opt/rfclient
-rm -r /var/lib/lxc/rfvmB/rootfs/opt/rfclient
-rm -r /var/lib/lxc/rfvmC/rootfs/opt/rfclient
-rm -r /var/lib/lxc/rfvmD/rootfs/opt/rfclient
-
-if [ "$1" != "clear" ]; then
-    echo "Starting MongoDB..."
+if [ "$ACTION" != "RESET" ]; then
+    echo "-> Starting MongoDB..."
     mkdir $HOME/db &>> $LOG_FILE
     mongod --quiet --dbpath $HOME/db --logpath /dev/null &
     sleep 3
 
-    echo "Starting the virtual machines..."
+    echo "-> Starting the virtual machines..."
     # Create the rfclient dir
     mkdir /var/lib/lxc/rfvmA/rootfs/opt/rfclient &>> $LOG_FILE
     mkdir /var/lib/lxc/rfvmB/rootfs/opt/rfclient &>> $LOG_FILE
@@ -107,7 +134,7 @@ if [ "$1" != "clear" ]; then
     lxc-start -n rfvmC -d &>> $LOG_FILE
     lxc-start -n rfvmD -d &>> $LOG_FILE
     
-    echo "Starting the management network (br0)..."
+    echo "-> Starting the management network (br0)..."
     sleep 5
 	ovs-vsctl add-br br0 \
 		-- add-port br0 rfvmA.0 \
@@ -117,15 +144,22 @@ if [ "$1" != "clear" ]; then
     ifconfig br0 up
     ifconfig br0 192.169.1.1
 
-    echo "Starting NOX and the RouteFlow network controller..."
-    ( cd nox/build/src && ./nox_core -i ptcp:6633 switchstats rfproxy topology --verbose="rfproxy:ANY:INFO" &>> $LOG_FILE & )
+    echo "-> Starting the controller ($ACTION) and RFPRoxy..."
+    case "$ACTION" in
+    POX)
+        ( cd pox && ./pox.py --no-cli log.level --=INFO topology openflow.topology openflow.discovery rfproxy & &>> $LOG_FILE & )
+        ;;
+    NOX)
+        ( cd nox/build/src && ./nox_core -i ptcp:6633 rfproxy --verbose="rfproxy:ANY:INFO" &>> $LOG_FILE & )
+        ;;
+    esac
     sleep 5
     
-    echo "Starting the RouteFlow server..."
+    echo "-> Starting the RFServer..."
     build/rfserver &>> $LOG_FILE &
     sleep 3
 
-    echo "Starting the control plane network (dp0 OVS)..."
+    echo "-> Starting the control plane network (dp0 VS)..."
 	ovs-vsctl add-br dp0 \
 		-- add-port dp0 rfvmA.1 \
 		-- add-port dp0 rfvmA.2 \
@@ -149,6 +183,7 @@ if [ "$1" != "clear" ]; then
     cd - &> /dev/null
     sleep 5
     
+    echo "---"
     echo "Now we'll open this test's log."
     echo "Start Mininet:"
     echo "  $ sudo mn --custom ~/mininet/custom/topo-4sw-4host.py --topo=rftopo"
@@ -157,8 +192,8 @@ if [ "$1" != "clear" ]; then
     echo "to the Mininet VM."
     echo "Then try pinging everything:"
     echo "  > pingall"
+    echo "You can stop this test by pressing CTRL+C."
+    echo "---"
     tail -f $LOG_FILE
 fi
-
 exit 0
-
